DROP TABLE IF EXISTS [dbo].[Class]
GO

CREATE TABLE [dbo].[Classes](
[Id] [UNIQUEIDENTIFIER] NOT NULL,
[ClassName] [NVARCHAR] (100) NOT NULL,
CONSTRAINT [PK_Classes] PRIMARY KEY CLUSTERED
(
[Id] ASC
)
WITH (STATISTICS_NORECOMPUTE =  OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]